---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgCWdTBjeulsUaJEOMnjdsFlSbVzKAP8l6v396CtCO2ACXQUU//W2AvZHDqmnTChaMjIMDI0h8zaDb+KMRmn1rvusheQLsgSfn24AT+I6eln81xzVuG68uLFsvxtcqra+56TvR7cZw6It6jqDpQ4thJKSr4n/QpHkgwIDFjKzitQl5EG7hOQWGlkRSe9VMVxinrVjBLcsyOa6nFOvNqBXWn+Py877TAzywSxVDFZVFrWhtcYX0R8xvs1EGJuccDYiZ68zyZHf06M7XxU6yp7FDEOPwmHITh8Cz10ZcH/FEpcPNmM6aaBYZrflPQZORhvSMHczazFdu+0kSpeqAlZmqU8UGdzMyTg9t9IeF0CwPtLeGNvfuylnosybNtNIfN6OY2BUFDfZS1UVKb6+TaBEE9nojbYvdZl+4I+QUh5rEIGB13KOHydEPos7b0JWdVLUdhMNUYd+MV93oryh1TaYWpD6QFWds/4o5Jo6rnWtTLuPncxDNHBy409oZ2wKoiiatKlgLQ02sibX2AdRie0phKiLOhKmizfOfRS3eeHDMlIGoMCDuNnKbL7Pl3nj7HFFQHt9JZmR8T8ClryJzBNXo1cZu78+r6x7wbDihmvTBkTc9trtBxhL77Ds8aAgHPC02fktYCTMIPSltZ8QIbqYogBOy6JXe+nX8222UadqYkP3rHZkCiN34JGSEibcWE9hBUGb29j1OvJ
    username: AgB35njay52Y4bHt9CrdYDrifINPgnGW/qJAAw2DnvB7nI/dqNVkPerT48uhm0sqEPaElt+vJKfA2pcJ2XTIfazAn0PFoC0Nlk+RMrtFBzTDqdUSk47OlaTPiR5x4EW9x/9sRPwrFN8INjTynXcVuGXohmR1JSXrSVwneogeMeypSKT9kzQl2rn0qu0RTZ7sd+AYyKl8Lpfy1MX96upFRpjcA1+K5VdpdelYMscbUy9Lk0zvA+5zmFZa5dg/kgMhcKZQo92nCvvQ3zkUb8JGcHx52ACGThHB9Xgyy4aAz1EAHit5v5t6HBFVI+Tp1F9+UVnc6sp6IogvHWIMXuMZ9NrrfwzzNEUZjXyWP91KOo+gdwt/t33kE6OnnOCkynY4s1exxgaWNoly2CQH+HF+dFyhC3/IvDHi1wbXu2OrhEb99eatfe1lGv2E0eEeQ6ieXar5rdbFYIOS567A4iM5RQOvMZFWJlGsgyAw6LbcbchkLh9JaDn0xBpQOes5XfjtCXkxx/CZ2bIM55k+UXO2R+9wAurWxoC0vl6Xe87iEm2l7NyRuMbFTFplSvZpG1UvqO1aSR4QFLvsjBCNKJbo8LF7mRevrnAqgsFT7I0gWFL3BaI4++uGcjiQbb+azBx3C55LeTxZ8DD9O/5AixQxhBAxXpGe6ph6cyvEzEXbb/P3OPJjlz9o1/jir7Aint+B/5JRTq3B9g==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
    type: Opaque
