---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgApftxyrv0X3OGKEblJgaN6eseLnKHm6khVn5NVeFGEHZ68NeWCStxp0rRptVlWDkmX/WFw2oaf5BGgWu22ShKQhrWF/fBar23dJaVluWlfl5/V8Zrhvi9Wk6yNkJuTd7Rhrg8XHNn3LU2+4tdrd3weMnZDoYg+u4zPki6aXnOc1Maq1lnePrv2NBJhVeSv7n19ifZB+i7yVI0T326+ReszNtx6aEXoU4rZ7kCCa2vBsnKW83k8ptNmwS0N425KYk/38Kkz6onzcTNWz+Mxm9YbUH6psQ7zR4xMRJJsp6YgAOioVXNcy+w/3KiDo+xgt/4G605JWvFVJ8gNH8DUm18/KqFt//n6+ranvk6zHAdqsia/WXL+BbyY9O1kBkFar/1uMDeQAOc8FoAx6ygwel9pWwZV7+5r9yXNKL8fbDOnYQ2WImi+yE3Aeern6CT+csPFUq970QP3+1dY8oDY1eDhEA5sV0A2ZjaohPhqbJ7FSSKvmVwlZ9dUw1dlCJ0dxC1mRSjbCClubE2/HajZxvUVRjiZR4IVcJzACOTmCkWhmXSeBrxvvXIgO0Iw9CaqEbvmQ15YT55d9OIU2DUwEf/1aXGhMRW1LaP0cCB8WiV4hWSJ2KZRiYGWqSw3cmH7N/qWWjm5Qe93RHqjb2b+LdbMCQctoWx+Ni+csvOa0xltAaTxxHzkb+ZOMthdffy4kcYInRnFvZXA
    username: AgA7ARX7Fltv7MMT0XRuxTN4hZchWAbyJYQbVIx8BzTzkvYZNhLRPeK5MVyJuRVyl3dFXAa4eHIcoKzuuM6aCfz9HoijthBbJEQoZD46IL8MWk5F+t60ozuzMHXxalX3FLDULIQDEfaLcl6avzocC9e5YgcPsMZjCqLSk8OTngfd/qfo61eumdUMEVAyaPIOGHRQgN0/7A11ct5unGwQQ9CDygSvu1xPnBefRdZauWDJvGAOJan/KYovLqEwslnF/87pw3dGeehOWtxopZnKOM14uzXgkOHTxSXUqgmSvjvDlUUPVA6eDsFRZw78xvft/4OOMx7FCj+munSDW8D3sqS8mnjvts9xm+EGJ/xEH5MQX1K1jjmpCC47g4tut6i7nbcnhb5FnM5t1BodzLnxsgON19Lw4jPduvVnv6sNcPz2iA/i77IW2L8i9qYWPUks14Xu9VPu5xkWqx19wrjFawSC0R7WobGQyxVeuuRenBFpkcEHrkCxLcu/uvnTOIXcRkx1xYWTPS8ru36P8iwAeKwZ/qH224lnTyI1BQlFr4IFWLMps0uL+doDzzNYPUzVpPGfDa4CMDYy7trSXSoPBh8T3s9BbxRL25OpzsamPZYR7e1CtXXwtdIxHqMTgA3WCGC+nNlNX45OcsjYUtPYBqwCCYs4Ft8dd+rHhEQoWsx2XYV1wMy9A0cip8UWZKgSjMK4wH18cw==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
