name: Pipeline_CI/CD

on:
  push:
    branches:
      - main

jobs:
  validate-terraform:
    name: Terraform Validation & tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Run tfsec (Terraform security scan)
        uses: aquasecurity/tfsec-action@v1.0.0